### ISSUE TITLE
issue 01

### ISSUE THREAD

**Issue by tohshige** [tohshige/test#1]
this is issue 

test
```javascript
var i=1;
```
```php
$i=1;
```
```
font-size:10px;
.white{
font-color:white;
}
```
色分け  
```css
font-size:10px;
.white{
font-color:white;
}
```
```bash
$vi Vagrantfile
#config.vm.network :private_network, ip: "192.168.33.10"
```
